[package]
name = "tw-referral"
description = "A standard referral controller that can query referral of specfic address and referral chains"
license = "Apache-2.0"
version = "0.1.0"
authors = ["TwilightCouncil"]
edition = "2021"
repositary = "https://github.com/TerraTwilightCouncil/twilight-standard"

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-std = { version = "0.16.5" }
cosmwasm-storage = { version = "0.16.5" }
cw-storage-plus = "0.9.1"
schemars = "0.8.8"
serde = { version = "1.0.136", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.5" }
