[package]
name = "referral"
description = "A standard referral controller that can query referral of specfic address and referral chains"
license = "Apache-2.0"
version = "0.1.0"
authors = ["TwilightCouncil"]
edition = "2021"

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-std = { version = "0.16.5" }
cosmwasm-storage = { version = "0.16.5" }
cw-storage-plus = "0.9.1"
cw2 = "0.9.1"
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.26" }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.5" }
cosmwasm-vm = { version = "0.16.5" }
terra-cosmwasm = { version = "2.2.0" }
rand = "0.8.3"
base64 = "0.13.0"
test-case = "2.0.0"
