[package]
name = "tw-asset-plus"
description = "Improved asset package with backward compatible from TerraSwap's Asset and Astroport's Asset"
version = "0.1.2"
license = "Apache-2.0"
authors = ["TwilightCouncil"]
edition = "2021"
repository = "https://github.com/TwilightCouncil/twilight-standard"

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-std = { version = "0.16.7" }
cosmwasm-storage = { version = "0.16.7" }
cw-storage-plus = "0.9.1"
cw20 = "0.9.1"
schemars = "0.8.8"
serde = { version = "1.0.136", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.5" }
